#
# This source file is part of the ENGAGE-HF-AI-Voice open source project
#
# SPDX-FileCopyrightText: 2022 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
# 


version: '3.8'

services:
  app:
    image: ghcr.io/stanfordbdhg/engage-hf-ai-voice:main
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - INTERNAL_TESTING_MODE=${INTERNAL_TESTING_MODE}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_API_KEY=${TWILIO_API_KEY}
      - TWILIO_SECRET=${TWILIO_SECRET}
    volumes:
      - "YOUR_ABSOLUTE_PATH:/app/Data"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    secrets:
      - twiliorecording_key

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network
    depends_on:
      - app
    secrets:
      - cert_chain
      - priv_key

  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup=true --interval 60

networks:
  app-network:
    driver: bridge

secrets:
  cert_chain:
    file: ./certs/certificate.pem
  priv_key:
    file: ./private/private.key
  twiliorecording_key:
    file: ./private/twiliorecording.key
