#
# This source file is part of the ENGAGE-HF-AI-Voice open source project
#
# SPDX-FileCopyrightText: 2022 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Build and Test

on:
  workflow_call:

jobs:
  reuse_action:
    name: REUSE Compliance Check
    uses: StanfordBDHG/.github/.github/workflows/reuse.yml@v2
  swiftlint:
    name: SwiftLint
    uses: StanfordBDHG/.github/.github/workflows/swiftlint.yml@v2
  packagemacos:
    name: Build and Test Swift Package macOS
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      scheme: App
      resultBundle: App-macOS.xcresult
      destination: 'platform=macOS,arch=arm64'
      artifactname: App-macOS.xcresult
  uploadcoveragereport:
    name: Upload Coverage Report
    needs: [packagemacos]
    uses: StanfordBDHG/.github/.github/workflows/create-and-upload-coverage-report.yml@v2
    with:
      coveragereports: App-macOS.xcresult
    secrets:
      token: ${{ secrets.CODECOV_TOKEN }}
