#
# This source file is part of the ENGAGE-HF-AI-Voice open source project
#
# SPDX-FileCopyrightText: 2022 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Build and Test

on:
  workflow_call:

jobs:
  reuse_action:
    name: REUSE Compliance Check
    uses: StanfordBDHG/.github/.github/workflows/reuse.yml@v2
  swiftlint:
    name: SwiftLint
    uses: StanfordBDHG/.github/.github/workflows/swiftlint.yml@v2
  buildandtestmacos:
    name: Build and Test
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    permissions:
      contents: read
    with:
      scheme: ENGAGE-HF-AI-Voice
      runsonlabels: '["macOS", "self-hosted"]'
      destination: 'platform=macOS,arch=arm64'
      artifactname: ENGAGE-HF-AI-Voice.xcresult
      resultBundle: ENGAGE-HF-AI-Voice.xcresult
    secrets:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  dockercomposetest:
    name: Docker Compose Test
    uses: StanfordBDHG/.github/.github/workflows/docker-compose-test.yml@v2
  uploadcoveragereport:
    name: Upload Coverage Report
    needs: [buildandtestmacos]
    uses: StanfordBDHG/.github/.github/workflows/create-and-upload-coverage-report.yml@v2
    with:
      coveragereports: ENGAGE-HF-AI-Voice.xcresult
    secrets:
      token: ${{ secrets.CODECOV_TOKEN }}
