#
# This source file is part of the ENGAGE-HF-AI-Voice open source project
#
# SPDX-FileCopyrightText: 2022 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Deployment

on:
  workflow_call:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  buildandpush:
    name: Build and Push to Container Registry
    uses: StanfordBDHG/.github/.github/workflows/docker-build-and-push.yml@v2
    secrets: inherit
    with:
      imageName: ghcr.io/stanfordbdhg/engage-hf-ai-voice
      version: ${{ github.event.release.tag_name || '' }}
